// Editable content in English. Change only the values after the colons.
window.PHYTOCHEM_CONTENT = window.PHYTOCHEM_CONTENT || {};
window.PHYTOCHEM_CONTENT.en = {
  "meta": {
    "lang": "en",
    "title": "PHYTOCHEM™ | R&D&I in Applied Botanical Science and Natural Bioactives",
    "description": "PHYTOCHEM™ transforms biodiversity into applied solutions backed by scientific evidence through natural bioactives, phytochemistry, isolation, traceability and industrial applications."
  },
  "links": {
    "siteUrl": "https://joelalbertofernandes.github.io/Phytochem/",
    "linkedinCompany": "https://www.linkedin.com/company/phytochemlab/",
    "instagram": "https://www.instagram.com/phytochem.lab/",
    "alineLinkedIn": "https://www.linkedin.com/in/alineborgesreche/",
    "ilzaLinkedIn": "https://www.linkedin.com/in/ilza-maria-oliveira-sousa-48b1352b9/",
    "commercialEmail": "comercial@phytochem.com.br",
    "linkedinCompanyLabel": "linkedin.com/company/phytochemlab",
    "instagramLabel": "@phytochem.lab"
  },
  "scheduler": {
    "defaultSubject": "B2B scientific conversation with PHYTOCHEM",
    "details": "Conversation about R&D&I in Applied Botanical Science and natural bioactive solutions."
  },
  "texts": {
    "Ir para o conteúdo": "Skip to content",
    "Início": "Home",
    "Sobre": "About",
    "Soluções": "Solutions",
    "Sustentabilidade": "Sustainability",
    "Corpo técnico": "Scientific team",
    "Contato": "Contact",
    "Agendar conversa": "Schedule a meeting",
    "Abrir menu": "Open menu",
    "Fechar menu": "Close menu",
    "// CIÊNCIA BOTÂNICA APLICADA": "// APPLIED BOTANICAL SCIENCE",
    "Bioativos naturais com": "Natural bioactives with",
    "evidência científica.": "scientific evidence.",
    "Transformamos biodiversidade em soluções aplicadas com evidências científicas.": "We transform biodiversity into applied solutions backed by scientific evidence.",
    "Conectamos biodiversidade, fitoquímica e tecnologia analítica ao desenvolvimento de soluções com bioativos naturais, rastreabilidade, isolamento e validação técnico-científica.": "We connect biodiversity, phytochemistry and analytical technology to develop solutions with natural bioactives, traceability, isolation and technical-scientific validation.",
    "Conheça nossas soluções": "Explore our solutions",
    "Pesquisa": "Research",
    "Fitoquímica": "Phytochemistry",
    "Isolamento": "Isolation",
    "Evidências": "Evidence",
    "Aplicações industriais": "Industrial applications",
    "Descobrir": "Discover",
    "// CONCEITO CENTRAL": "// CORE CONCEPT",
    "A natureza sempre teve respostas.": "Nature has always had answers.",
    "A ciência agora permite decodificá-las.": "Science now allows us to decode them.",
    "A Phytochem une P&DI, fitoquímica aplicada e tecnologia analítica para transformar biodiversidade em soluções com bioativos naturais, evidências técnicas, rastreabilidade e aplicações industriais.": "Phytochem combines R&D&I, applied phytochemistry and analytical technology to transform biodiversity into solutions with natural bioactives, technical evidence, traceability and industrial applications.",
    "Mais do que um laboratório, atuamos como uma plataforma científica para o desenvolvimento de soluções naturais com precisão, método, evidências e visão de mercado.": "More than a laboratory, we operate as a scientific platform for developing natural solutions with precision, method, evidence and market vision.",
    "Soluções científicas para bioativos naturais": "Scientific solutions for natural bioactives",
    "Da análise ao desenvolvimento: suporte técnico para empresas que desejam criar, validar, padronizar e escalar soluções com bioativos naturais.": "From analysis to development: technical support for companies seeking to create, validate, standardize and scale natural bioactive solutions.",
    "Análise fitoquímica": "Phytochemical analysis",
    "Identificação, caracterização e avaliação de compostos presentes em matrizes naturais.": "Identification, characterization and evaluation of compounds in natural matrices.",
    "Fitoquímica aplicada →": "Applied phytochemistry →",
    "Mapeamos e caracterizamos o perfil químico de insumos e matrizes naturais, apoiando decisões técnicas e geração de evidências.": "We map and characterize the chemical profile of natural inputs and matrices, supporting technical decisions and evidence generation.",
    "Saiba mais →": "Learn more →",
    "Desenvolvimento de produtos com bioativos": "Bioactive product development",
    "Soluções para aplicações cosméticas, farmacêuticas e industriais.": "Solutions for cosmetic, pharmaceutical and industrial applications.",
    "Inovação e P&DI →": "Innovation and R&D&I →",
    "Desenvolvimento com bioativos": "Bioactive development",
    "Conectamos seleção de insumos, evidências, padronização, viabilidade técnica e direcionamento de aplicação.": "We connect input selection, evidence, standardization, technical feasibility and application strategy.",
    "Padronização de extratos": "Extract standardization",
    "Parâmetros técnicos, fingerprints, especificações e controle de qualidade.": "Technical parameters, fingerprints, specifications and quality control.",
    "Garantia técnica →": "Technical assurance →",
    "Estruturamos processos para assegurar consistência, repetibilidade analítica, rastreabilidade e desempenho industrial.": "We structure processes to ensure consistency, analytical repeatability, traceability and industrial performance.",
    "Química analítica e evidências": "Analytical chemistry and evidence",
    "Métodos analíticos voltados ao controle, validação e geração de evidências.": "Analytical methods for control, validation and evidence generation.",
    "Evidências científicas →": "Scientific evidence →",
    "Química analítica": "Analytical chemistry",
    "Aplicamos química analítica para apoiar controle, validação, estudos comparativos e geração de evidências técnicas.": "We apply analytical chemistry to support control, validation, comparative studies and technical evidence generation.",
    "Pesquisa aplicada e desenvolvimento": "Applied research and development",
    "Suporte científico para projetos orientados à inovação e aplicações.": "Scientific support for innovation and application-driven projects.",
    "Pesquisa aplicada →": "Applied research →",
    "Pesquisa aplicada": "Applied research",
    "Transformamos biodiversidade em soluções com valor técnico e potencial de mercado por meio de ciência aplicada.": "We transform biodiversity into solutions with technical value and market potential through applied science.",
    "Consultoria científica B2B": "B2B scientific consulting",
    "Orientação estratégica para desenvolver, validar e posicionar soluções.": "Strategic guidance to develop, validate and position solutions.",
    "Estratégia científica →": "Scientific strategy →",
    "Estruturamos caminhos de desenvolvimento, priorização de estudos, aplicações e diferenciação científica.": "We structure development paths, study prioritization, applications and scientific differentiation.",
    "PRODUÇÃO DE CONHECIMENTO": "KNOWLEDGE PRODUCTION",
    "P&DI em Ciência Botânica Aplicada": "R&D&I in Applied Botanical Science",
    "Integramos ciência, dados, biodiversidade e tecnologia para acelerar o desenvolvimento de soluções com bioativos naturais.": "We integrate science, data, biodiversity and technology to accelerate natural bioactive solution development.",
    "Leitura científica da biodiversidade": "Scientific reading of biodiversity",
    "Análise técnica para identificar oportunidades estruturadas em bioativos naturais e aplicações de alto valor.": "Technical analysis to identify structured opportunities in natural bioactives and high-value applications.",
    "P&D orientado por dados": "Data-driven R&D",
    "Pesquisa analítica guiada por dados, evidências e caracterização molecular.": "Analytical research guided by data, evidence and molecular characterization.",
    "Extração e isolamento de precisão": "Precision extraction and isolation",
    "Frações direcionadas com foco em rendimento, estabilidade fitoquímica e aplicação.": "Targeted fractions focused on yield, phytochemical stability and application.",
    "Validação técnico-científica": "Technical-scientific validation",
    "Evidências consistentes para transformar descobertas naturais em soluções aplicáveis.": "Consistent evidence to transform natural discoveries into applicable solutions.",
    "ROADMAP CIENTÍFICO": "SCIENTIFIC ROADMAP",
    "Pipeline Phytochem de Inovação Aplicada": "Phytochem Applied Innovation Pipeline",
    "Da biodiversidade às aplicações com bioativos naturais, por meio de evidências, isolamento, validação e direcionamento técnico.": "From biodiversity to natural bioactive applications through evidence, isolation, validation and technical direction.",
    "Descoberta": "Discovery",
    "Caracterização": "Characterization",
    "Validação": "Validation",
    "Aplicação": "Application",
    "Escala": "Scale",
    "Biodiversidade": "Biodiversity",
    "Seleção botânica": "Botanical selection",
    "Extração": "Extraction",
    "Transferência": "Transfer",
    "PIPELINE EXCLUSIVA": "EXCLUSIVE PIPELINE",
    "Isolamento de Compostos Bioativos": "Bioactive Compound Isolation",
    "Uma jornada científica independente, orientada à obtenção, purificação e validação de compostos naturais com precisão analítica.": "An independent scientific journey focused on obtaining, purifying and validating natural compounds with analytical precision.",
    "Coleta Botânica": "Botanical Collection",
    "Origem responsável e seleção criteriosa.": "Responsible origin and careful selection.",
    "Preparação da Matéria-Prima": "Raw Material Preparation",
    "Tratamento técnico para preservar o potencial químico.": "Technical treatment to preserve chemical potential.",
    "Processos dirigidos por rendimento e seletividade.": "Processes driven by yield and selectivity.",
    "Fracionamento": "Fractionation",
    "Separação orientada pelo perfil fitoquímico.": "Separation guided by the phytochemical profile.",
    "Purificação": "Purification",
    "Refinamento progressivo de frações de interesse.": "Progressive refinement of fractions of interest.",
    "Obtenção de compostos com identidade definida.": "Obtaining compounds with defined identity.",
    "Caracterização Analítica": "Analytical Characterization",
    "Elucidação e confirmação técnico-analítica.": "Technical-analytical elucidation and confirmation.",
    "Validação Científica": "Scientific Validation",
    "Evidências consistentes para aplicações futuras.": "Consistent evidence for future applications.",
    "Projeto P&DI 01": "R&D&I Project 01",
    "Isolamento e caracterização de frações bioativas": "Isolation and characterization of bioactive fractions",
    "Produto / aplicação": "Product / application",
    "Transferência B2B": "B2B transfer",
    "◈ Propriedade intelectual": "◈ Intellectual property",
    "⌁ Codesenvolvimento": "⌁ Co-development",
    "▤ Evidências técnico-científicas": "▤ Technical-scientific evidence",
    "⚗ Aplicação industrial": "⚗ Industrial application",
    "⚙ Transferência tecnológica": "⚙ Technology transfer",
    "MERCADOS-CHAVE": "KEY MARKETS",
    "Onde os bioativos naturais geram valor": "Where natural bioactives create value",
    "Soluções rastreáveis e suporte técnico-científico para mercados de alta exigência.": "Traceable solutions and technical-scientific support for highly demanding markets.",
    "Cosméticos e dermocosméticos": "Cosmetics and dermocosmetics",
    "Suplementos e alimentos funcionais": "Supplements and functional foods",
    "Farmacêutico e saúde": "Pharmaceutical and health",
    "Ingredientes naturais e funcionais": "Natural and functional ingredients",
    "Indústria de ingredientes": "Ingredients industry",
    "Pesquisa acadêmica e aplicada": "Academic and applied research",
    "Bioativos naturais e suporte técnico para formulações premium.": "Natural bioactives and technical support for premium formulations.",
    "Compostos naturais, padronização e suporte ao desenvolvimento.": "Natural compounds, standardization and development support.",
    "Pesquisa, isolamento, validação e documentação de alto rigor.": "High-rigor research, isolation, validation and documentation.",
    "Diferenciação científica para produtos de valor agregado.": "Scientific differentiation for value-added products.",
    "Ingredientes naturais rastreáveis, consistentes e diferenciados.": "Traceable, consistent and differentiated natural ingredients.",
    "Apoio a universidades, startups e projetos colaborativos.": "Support for universities, startups and collaborative projects.",
    "// METODOLOGIA SUSTENTÁVEL": "// SUSTAINABLE METHODOLOGY",
    "Ciência natural com responsabilidade": "Natural science with responsibility",
    "Sustentabilidade como método: origem responsável, rastreabilidade, eficiência, valorização da biodiversidade e menor impacto ambiental.": "Sustainability as a method: responsible sourcing, traceability, efficiency, biodiversity appreciation and lower environmental impact.",
    "Biodiversidade brasileira": "Brazilian biodiversity",
    "Cadeias locais": "Local value chains",
    "Saberes tradicionais": "Traditional knowledge",
    "Rastreabilidade": "Traceability",
    "Valorização de resíduos": "Waste valorization",
    "Valorização científica, legal e sustentável dos recursos naturais.": "Scientific, legal and sustainable valorization of natural resources.",
    "Integração responsável com territórios produtivos e parceiros.": "Responsible integration with productive territories and partners.",
    "Abordagem ética, respeito cultural e observância legal.": "Ethical approach, cultural respect and legal compliance.",
    "Eficiência, redução de resíduos e racionalidade técnica.": "Efficiency, waste reduction and technical rationality.",
    "Controle documental desde a origem até a aplicação.": "Document control from origin to application.",
    "Upcycling de coprodutos em novas oportunidades de aplicação.": "Upcycling co-products into new application opportunities.",
    "HUB EDITORIAL": "EDITORIAL HUB",
    "Insights Científicos": "Scientific Insights",
    "Conhecimento e evidências para empresas e parceiros que priorizam inovação botânica aplicada.": "Knowledge and evidence for companies and partners prioritizing applied botanical innovation.",
    "FITOQUÍMICA APLICADA · 6 MIN": "APPLIED PHYTOCHEMISTRY · 6 MIN",
    "EVIDÊNCIAS · 5 MIN": "EVIDENCE · 5 MIN",
    "Da matriz natural ao fingerprint: por que padronizar?": "From natural matrix to fingerprint: why standardize?",
    "Consistência analítica como base para inovação com bioativos.": "Analytical consistency as a foundation for bioactive innovation.",
    "Evidências técnicas que fortalecem decisões B2B": "Technical evidence that strengthens B2B decisions",
    "O papel da química analítica na confiança e diferenciação.": "The role of analytical chemistry in trust and differentiation.",
    "Como transformar biodiversidade em aplicação": "How to transform biodiversity into application",
    "Um caminho orientado por ciência, dados e visão de mercado.": "A path guided by science, data and market vision.",
    "Ver todas as publicações →": "View all publications →",
    "CORPO TÉCNICO": "SCIENTIFIC TEAM",
    "Liderança científica para soluções com bioativos naturais": "Scientific leadership for natural bioactive solutions",
    "Parceiras estratégicas para empresas, laboratórios e instituições que buscam rigor técnico, evidências e inovação aplicada.": "Strategic partners for companies, laboratories and institutions seeking technical rigor, evidence and applied innovation.",
    "Pesquisa biomédica, P&DI e qualidade científica.": "Biomedical research, R&D&I and scientific quality.",
    "Liderança científica e empreendedora com atuação em pesquisa, desenvolvimento e estruturação de soluções com bioativos naturais.": "Scientific and entrepreneurial leadership in research, development and structuring natural bioactive solutions.",
    "Fitoquímica, produtos naturais e ciência botânica aplicada.": "Phytochemistry, natural products and applied botanical science.",
    "Pesquisadora com ampla experiência em produtos naturais, fitoquímica aplicada e desenvolvimento científico.": "Researcher with extensive experience in natural products, applied phytochemistry and scientific development.",
    "Ver LinkedIn →": "View LinkedIn →",
    "CONEXÕES OFICIAIS": "OFFICIAL CHANNELS",
    "Canais institucionais": "Institutional channels",
    "Conecte-se com a PHYTOCHEM™ por nossos canais oficiais.": "Connect with PHYTOCHEM™ through our official channels.",
    "LinkedIn Corporativo": "Corporate LinkedIn",
    "Instagram Oficial": "Official Instagram",
    "E-mail Comercial": "Commercial email",
    "RECONHECIMENTOS E VINCULAÇÕES INSTITUCIONAIS": "RECOGNITION AND INSTITUTIONAL AFFILIATIONS",
    "Ciência conectada a um ecossistema de inovação.": "Science connected to an innovation ecosystem.",
    "A PHYTOCHEM™ integra a rede de empresas-filhas da Unicamp, fortalecendo sua conexão com pesquisa, empreendedorismo científico e inovação aplicada.": "PHYTOCHEM™ is part of Unicamp's daughter-company network, strengthening its connection with research, scientific entrepreneurship and applied innovation.",
    "// CONEXÃO CIENTÍFICA B2B": "// B2B SCIENTIFIC CONNECTION",
    "Vamos transformar biodiversidade em soluções com evidência científica?": "Shall we transform biodiversity into solutions backed by scientific evidence?",
    "Converse com a PHYTOCHEM™ para estruturar, validar ou desenvolver soluções com bioativos naturais, rastreabilidade técnica e visão de mercado.": "Talk to PHYTOCHEM™ to structure, validate or develop natural bioactive solutions with technical traceability and market vision.",
    "Falar com a Phytochem": "Talk to Phytochem",
    "Conhecer soluções": "Explore solutions",
    "Navegação": "Navigation",
    "Conexões Oficiais": "Official Channels",
    "P&DI em Ciência Botânica Aplicada.": "R&D&I in Applied Botanical Science.",
    "Bioativos naturais com evidência científica.": "Natural bioactives backed by scientific evidence.",
    "Ciência · Rastreabilidade · Evidência": "Science · Traceability · Evidence",
    "AGENDA B2B": "B2B SCHEDULING",
    "Agende uma conversa científica": "Schedule a scientific conversation",
    "Escolha uma data e um horário. Ao continuar, o Google Calendar abrirá o convite com a equipe comercial da PHYTOCHEM™.": "Choose a date and time. When you continue, Google Calendar will open an invitation with the PHYTOCHEM™ commercial team.",
    "Data": "Date",
    "Horário": "Time",
    "Duração": "Duration",
    "Assunto": "Subject",
    "45 minutos": "45 minutes",
    "60 minutos": "60 minutes",
    "Continuar no Google Calendar": "Continue to Google Calendar",
    "O convite será preparado com comercial@phytochem.com.br como participante.": "The invitation will be prepared with comercial@phytochem.com.br as a participant.",
    "Fechar agenda": "Close scheduler",
    "Ex.: Projeto com bioativos naturais": "E.g.: Natural bioactive project",
    "PHYTOCHEM™ | P&DI em Ciência Botânica Aplicada e Bioativos Naturais": "PHYTOCHEM™ | P&DI em Ciência Botânica Aplicada e Bioativos Naturais",
    "P&DI": "P&DI",
    "Insights": "Insights",
    "PT": "PT",
    "EN": "EN",
    "ES": "ES",
    "PHYTOCHEM™": "PHYTOCHEM™",
    "•": "•",
    "B2B CAPABILITIES": "B2B CAPABILITIES",
    "01": "01",
    "02": "02",
    "03": "03",
    "04": "04",
    "05": "05",
    "06": "06",
    "01 / DESCOBRIR": "01 / DESCOBRIR",
    "02 / DECODIFICAR": "02 / DECODIFICAR",
    "03 / ISOLAR": "03 / ISOLAR",
    "04 / VALIDAR": "04 / VALIDAR",
    "07": "07",
    "08": "08",
    "09": "09",
    "⌁": "⌁",
    "◇": "◇",
    "⚗": "⚗",
    "≋": "≋",
    "◈": "◈",
    "◎": "◎",
    "⌬": "⌬",
    "✓": "✓",
    "Green Chemistry": "Green Chemistry",
    "P&DI · 8 MIN": "P&DI · 8 MIN",
    "CEO & FOUNDER": "CEO & FOUNDER",
    "Aline Borges Reche": "Aline Borges Reche",
    "CHIEF SCIENTIFIC OFFICER": "CHIEF SCIENTIFIC OFFICER",
    "Ilza Maria Oliveira Sousa": "Ilza Maria Oliveira Sousa",
    "in": "in",
    "linkedin.com/company/phytochemlab": "linkedin.com/company/phytochemlab",
    "@phytochem.lab": "@phytochem.lab",
    "@": "@",
    "comercial@phytochem.com.br": "comercial@phytochem.com.br",
    "×": "×",
    "© PHYTOCHEM™. Todos os direitos reservados.": "© PHYTOCHEM™. Todos os direitos reservados.",
    "PHYTOCHEM - início": "PHYTOCHEM - início",
    "PHYTOCHEM": "PHYTOCHEM",
    "Navegação principal": "Navegação principal",
    "Selecionar idioma": "Selecionar idioma",
    "Português": "Português",
    "English": "English",
    "Español": "Español",
    "Pipeline de inovação": "Pipeline de inovação",
    "Pipeline de isolamento de compostos bioativos": "Pipeline de isolamento de compostos bioativos",
    "Cadeia botânica responsável integrada a processos científicos sustentáveis": "Cadeia botânica responsável integrada a processos científicos sustentáveis",
    "Extrato botânico e fingerprint fitoquímico": "Extrato botânico e fingerprint fitoquímico",
    "Instrumentação analítica gerando evidências científicas": "Instrumentação analítica gerando evidências científicas",
    "Espécime botânico conectado à pesquisa aplicada": "Espécime botânico conectado à pesquisa aplicada",
    "Aline Borges Reche, CEO e fundadora da Phytochem": "Aline Borges Reche, CEO e fundadora da Phytochem",
    "Ilza Maria Oliveira Sousa, Chief Scientific Officer da Phytochem": "Ilza Maria Oliveira Sousa, Chief Scientific Officer da Phytochem",
    "Selo oficial Empresa-Filha da Unicamp": "Selo oficial Empresa-Filha da Unicamp"
  }
};
