// Contenido editable en espanol. Cambie solamente los valores despues de los dos puntos.
window.PHYTOCHEM_CONTENT = window.PHYTOCHEM_CONTENT || {};
window.PHYTOCHEM_CONTENT.es = {
  "meta": {
    "lang": "es",
    "title": "PHYTOCHEM™ | I+D+i en Ciencia Botánica Aplicada y Bioactivos Naturales",
    "description": "PHYTOCHEM™ transforma la biodiversidad en soluciones aplicadas con evidencia científica mediante bioactivos naturales, fitoquímica, aislamiento, trazabilidad y aplicaciones industriales."
  },
  "links": {
    "siteUrl": "https://joelalbertofernandes.github.io/Phytochem/",
    "linkedinCompany": "https://www.linkedin.com/company/phytochemlab/",
    "instagram": "https://www.instagram.com/phytochem.lab/",
    "alineLinkedIn": "https://www.linkedin.com/in/alineborgesreche/",
    "ilzaLinkedIn": "https://www.linkedin.com/in/ilza-maria-oliveira-sousa-48b1352b9/",
    "commercialEmail": "comercial@phytochem.com.br",
    "linkedinCompanyLabel": "linkedin.com/company/phytochemlab",
    "instagramLabel": "@phytochem.lab"
  },
  "scheduler": {
    "defaultSubject": "Conversación científica B2B con PHYTOCHEM",
    "details": "Conversación sobre I+D+i en Ciencia Botánica Aplicada y soluciones con bioactivos naturales."
  },
  "texts": {
    "Ir para o conteúdo": "Ir al contenido",
    "Início": "Inicio",
    "Sobre": "Acerca de",
    "Soluções": "Soluciones",
    "Sustentabilidade": "Sostenibilidad",
    "Corpo técnico": "Equipo científico",
    "Contato": "Contacto",
    "Agendar conversa": "Agendar una reunión",
    "Abrir menu": "Abrir menú",
    "Fechar menu": "Cerrar menú",
    "// CIÊNCIA BOTÂNICA APLICADA": "// CIENCIA BOTÁNICA APLICADA",
    "Bioativos naturais com": "Bioactivos naturales con",
    "evidência científica.": "evidencia científica.",
    "Transformamos biodiversidade em soluções aplicadas com evidências científicas.": "Transformamos la biodiversidad en soluciones aplicadas con evidencia científica.",
    "Conectamos biodiversidade, fitoquímica e tecnologia analítica ao desenvolvimento de soluções com bioativos naturais, rastreabilidade, isolamento e validação técnico-científica.": "Conectamos biodiversidad, fitoquímica y tecnología analítica para desarrollar soluciones con bioactivos naturales, trazabilidad, aislamiento y validación técnico-científica.",
    "Conheça nossas soluções": "Conozca nuestras soluciones",
    "Pesquisa": "Investigación",
    "Fitoquímica": "Fitoquímica",
    "Isolamento": "Aislamiento",
    "Evidências": "Evidencias",
    "Aplicações industriais": "Aplicaciones industriales",
    "Descobrir": "Descubrir",
    "// CONCEITO CENTRAL": "// CONCEPTO CENTRAL",
    "A natureza sempre teve respostas.": "La naturaleza siempre ha tenido respuestas.",
    "A ciência agora permite decodificá-las.": "La ciencia ahora permite decodificarlas.",
    "A Phytochem une P&DI, fitoquímica aplicada e tecnologia analítica para transformar biodiversidade em soluções com bioativos naturais, evidências técnicas, rastreabilidade e aplicações industriais.": "Phytochem integra I+D+i, fitoquímica aplicada y tecnología analítica para transformar la biodiversidad en soluciones con bioactivos naturales, evidencia técnica, trazabilidad y aplicaciones industriales.",
    "Mais do que um laboratório, atuamos como uma plataforma científica para o desenvolvimento de soluções naturais com precisão, método, evidências e visão de mercado.": "Más que un laboratorio, actuamos como una plataforma científica para desarrollar soluciones naturales con precisión, método, evidencia y visión de mercado.",
    "Soluções científicas para bioativos naturais": "Soluciones científicas para bioactivos naturales",
    "Da análise ao desenvolvimento: suporte técnico para empresas que desejam criar, validar, padronizar e escalar soluções com bioativos naturais.": "Del análisis al desarrollo: soporte técnico para empresas que buscan crear, validar, estandarizar y escalar soluciones con bioactivos naturales.",
    "Análise fitoquímica": "Análisis fitoquímico",
    "Identificação, caracterização e avaliação de compostos presentes em matrizes naturais.": "Identificación, caracterización y evaluación de compuestos presentes en matrices naturales.",
    "Fitoquímica aplicada →": "Fitoquímica aplicada →",
    "Mapeamos e caracterizamos o perfil químico de insumos e matrizes naturais, apoiando decisões técnicas e geração de evidências.": "Mapeamos y caracterizamos el perfil químico de insumos y matrices naturales, apoyando decisiones técnicas y generación de evidencia.",
    "Saiba mais →": "Más información →",
    "Desenvolvimento de produtos com bioativos": "Desarrollo de productos con bioactivos",
    "Soluções para aplicações cosméticas, farmacêuticas e industriais.": "Soluciones para aplicaciones cosméticas, farmacéuticas e industriales.",
    "Inovação e P&DI →": "Innovación e I+D+i →",
    "Desenvolvimento com bioativos": "Desarrollo con bioactivos",
    "Conectamos seleção de insumos, evidências, padronização, viabilidade técnica e direcionamento de aplicação.": "Conectamos selección de insumos, evidencia, estandarización, viabilidad técnica y estrategia de aplicación.",
    "Padronização de extratos": "Estandarización de extractos",
    "Parâmetros técnicos, fingerprints, especificações e controle de qualidade.": "Parámetros técnicos, fingerprints, especificaciones y control de calidad.",
    "Garantia técnica →": "Garantía técnica →",
    "Estruturamos processos para assegurar consistência, repetibilidade analítica, rastreabilidade e desempenho industrial.": "Estructuramos procesos para asegurar consistencia, repetibilidad analítica, trazabilidad y desempeño industrial.",
    "Química analítica e evidências": "Química analítica y evidencia",
    "Métodos analíticos voltados ao controle, validação e geração de evidências.": "Métodos analíticos orientados al control, validación y generación de evidencia.",
    "Evidências científicas →": "Evidencia científica →",
    "Química analítica": "Química analítica",
    "Aplicamos química analítica para apoiar controle, validação, estudos comparativos e geração de evidências técnicas.": "Aplicamos química analítica para apoyar control, validación, estudios comparativos y generación de evidencia técnica.",
    "Pesquisa aplicada e desenvolvimento": "Investigación aplicada y desarrollo",
    "Suporte científico para projetos orientados à inovação e aplicações.": "Soporte científico para proyectos orientados a innovación y aplicaciones.",
    "Pesquisa aplicada →": "Investigación aplicada →",
    "Pesquisa aplicada": "Investigación aplicada",
    "Transformamos biodiversidade em soluções com valor técnico e potencial de mercado por meio de ciência aplicada.": "Transformamos biodiversidad en soluciones con valor técnico y potencial de mercado mediante ciencia aplicada.",
    "Consultoria científica B2B": "Consultoría científica B2B",
    "Orientação estratégica para desenvolver, validar e posicionar soluções.": "Orientación estratégica para desarrollar, validar y posicionar soluciones.",
    "Estratégia científica →": "Estrategia científica →",
    "Estruturamos caminhos de desenvolvimento, priorização de estudos, aplicações e diferenciação científica.": "Estructuramos rutas de desarrollo, priorización de estudios, aplicaciones y diferenciación científica.",
    "PRODUÇÃO DE CONHECIMENTO": "PRODUCCIÓN DE CONOCIMIENTO",
    "P&DI em Ciência Botânica Aplicada": "I+D+i en Ciencia Botánica Aplicada",
    "Integramos ciência, dados, biodiversidade e tecnologia para acelerar o desenvolvimento de soluções com bioativos naturais.": "Integramos ciencia, datos, biodiversidad y tecnología para acelerar el desarrollo de soluciones con bioactivos naturales.",
    "Leitura científica da biodiversidade": "Lectura científica de la biodiversidad",
    "Análise técnica para identificar oportunidades estruturadas em bioativos naturais e aplicações de alto valor.": "Análisis técnico para identificar oportunidades estructuradas en bioactivos naturales y aplicaciones de alto valor.",
    "P&D orientado por dados": "I+D orientada por datos",
    "Pesquisa analítica guiada por dados, evidências e caracterização molecular.": "Investigación analítica guiada por datos, evidencia y caracterización molecular.",
    "Extração e isolamento de precisão": "Extracción y aislamiento de precisión",
    "Frações direcionadas com foco em rendimento, estabilidade fitoquímica e aplicação.": "Fracciones dirigidas con enfoque en rendimiento, estabilidad fitoquímica y aplicación.",
    "Validação técnico-científica": "Validación técnico-científica",
    "Evidências consistentes para transformar descobertas naturais em soluções aplicáveis.": "Evidencia consistente para transformar descubrimientos naturales en soluciones aplicables.",
    "ROADMAP CIENTÍFICO": "ROADMAP CIENTÍFICO",
    "Pipeline Phytochem de Inovação Aplicada": "Pipeline Phytochem de Innovación Aplicada",
    "Da biodiversidade às aplicações com bioativos naturais, por meio de evidências, isolamento, validação e direcionamento técnico.": "De la biodiversidad a las aplicaciones con bioactivos naturales mediante evidencia, aislamiento, validación y orientación técnica.",
    "Descoberta": "Descubrimiento",
    "Caracterização": "Caracterización",
    "Validação": "Validación",
    "Aplicação": "Aplicación",
    "Escala": "Escala",
    "Biodiversidade": "Biodiversidad",
    "Seleção botânica": "Selección botánica",
    "Extração": "Extracción",
    "Transferência": "Transferencia",
    "PIPELINE EXCLUSIVA": "PIPELINE EXCLUSIVA",
    "Isolamento de Compostos Bioativos": "Aislamiento de Compuestos Bioactivos",
    "Uma jornada científica independente, orientada à obtenção, purificação e validação de compostos naturais com precisão analítica.": "Una jornada científica independiente orientada a la obtención, purificación y validación de compuestos naturales con precisión analítica.",
    "Coleta Botânica": "Recolección Botánica",
    "Origem responsável e seleção criteriosa.": "Origen responsable y selección rigurosa.",
    "Preparação da Matéria-Prima": "Preparación de la Materia Prima",
    "Tratamento técnico para preservar o potencial químico.": "Tratamiento técnico para preservar el potencial químico.",
    "Processos dirigidos por rendimento e seletividade.": "Procesos orientados por rendimiento y selectividad.",
    "Fracionamento": "Fraccionamiento",
    "Separação orientada pelo perfil fitoquímico.": "Separación orientada por el perfil fitoquímico.",
    "Purificação": "Purificación",
    "Refinamento progressivo de frações de interesse.": "Refinamiento progresivo de fracciones de interés.",
    "Obtenção de compostos com identidade definida.": "Obtención de compuestos con identidad definida.",
    "Caracterização Analítica": "Caracterización Analítica",
    "Elucidação e confirmação técnico-analítica.": "Elucidación y confirmación técnico-analítica.",
    "Validação Científica": "Validación Científica",
    "Evidências consistentes para aplicações futuras.": "Evidencia consistente para aplicaciones futuras.",
    "Projeto P&DI 01": "Proyecto I+D+i 01",
    "Isolamento e caracterização de frações bioativas": "Aislamiento y caracterización de fracciones bioactivas",
    "Produto / aplicação": "Producto / aplicación",
    "Transferência B2B": "Transferencia B2B",
    "◈ Propriedade intelectual": "◈ Propiedad intelectual",
    "⌁ Codesenvolvimento": "⌁ Codesarrollo",
    "▤ Evidências técnico-científicas": "▤ Evidencia técnico-científica",
    "⚗ Aplicação industrial": "⚗ Aplicación industrial",
    "⚙ Transferência tecnológica": "⚙ Transferencia tecnológica",
    "MERCADOS-CHAVE": "MERCADOS CLAVE",
    "Onde os bioativos naturais geram valor": "Donde los bioactivos naturales generan valor",
    "Soluções rastreáveis e suporte técnico-científico para mercados de alta exigência.": "Soluciones trazables y soporte técnico-científico para mercados de alta exigencia.",
    "Cosméticos e dermocosméticos": "Cosméticos y dermocosméticos",
    "Suplementos e alimentos funcionais": "Suplementos y alimentos funcionales",
    "Farmacêutico e saúde": "Farmacéutico y salud",
    "Ingredientes naturais e funcionais": "Ingredientes naturales y funcionales",
    "Indústria de ingredientes": "Industria de ingredientes",
    "Pesquisa acadêmica e aplicada": "Investigación académica y aplicada",
    "Bioativos naturais e suporte técnico para formulações premium.": "Bioactivos naturales y soporte técnico para formulaciones premium.",
    "Compostos naturais, padronização e suporte ao desenvolvimento.": "Compuestos naturales, estandarización y soporte al desarrollo.",
    "Pesquisa, isolamento, validação e documentação de alto rigor.": "Investigación, aislamiento, validación y documentación de alto rigor.",
    "Diferenciação científica para produtos de valor agregado.": "Diferenciación científica para productos de valor agregado.",
    "Ingredientes naturais rastreáveis, consistentes e diferenciados.": "Ingredientes naturales trazables, consistentes y diferenciados.",
    "Apoio a universidades, startups e projetos colaborativos.": "Apoyo a universidades, startups y proyectos colaborativos.",
    "// METODOLOGIA SUSTENTÁVEL": "// METODOLOGÍA SOSTENIBLE",
    "Ciência natural com responsabilidade": "Ciencia natural con responsabilidad",
    "Sustentabilidade como método: origem responsável, rastreabilidade, eficiência, valorização da biodiversidade e menor impacto ambiental.": "Sostenibilidad como método: origen responsable, trazabilidad, eficiencia, valorización de la biodiversidad y menor impacto ambiental.",
    "Biodiversidade brasileira": "Biodiversidad brasileña",
    "Cadeias locais": "Cadenas locales",
    "Saberes tradicionais": "Conocimientos tradicionales",
    "Rastreabilidade": "Trazabilidad",
    "Valorização de resíduos": "Valorización de residuos",
    "Valorização científica, legal e sustentável dos recursos naturais.": "Valorización científica, legal y sostenible de los recursos naturales.",
    "Integração responsável com territórios produtivos e parceiros.": "Integración responsable con territorios productivos y socios.",
    "Abordagem ética, respeito cultural e observância legal.": "Enfoque ético, respeto cultural y cumplimiento legal.",
    "Eficiência, redução de resíduos e racionalidade técnica.": "Eficiencia, reducción de residuos y racionalidad técnica.",
    "Controle documental desde a origem até a aplicação.": "Control documental desde el origen hasta la aplicación.",
    "Upcycling de coprodutos em novas oportunidades de aplicação.": "Upcycling de coproductos en nuevas oportunidades de aplicación.",
    "HUB EDITORIAL": "HUB EDITORIAL",
    "Insights Científicos": "Insights Científicos",
    "Conhecimento e evidências para empresas e parceiros que priorizam inovação botânica aplicada.": "Conocimiento y evidencia para empresas y socios que priorizan innovación botánica aplicada.",
    "FITOQUÍMICA APLICADA · 6 MIN": "FITOQUÍMICA APLICADA · 6 MIN",
    "EVIDÊNCIAS · 5 MIN": "EVIDENCIA · 5 MIN",
    "Da matriz natural ao fingerprint: por que padronizar?": "De la matriz natural al fingerprint: ¿por qué estandarizar?",
    "Consistência analítica como base para inovação com bioativos.": "Consistencia analítica como base para la innovación con bioactivos.",
    "Evidências técnicas que fortalecem decisões B2B": "Evidencia técnica que fortalece decisiones B2B",
    "O papel da química analítica na confiança e diferenciação.": "El papel de la química analítica en la confianza y diferenciación.",
    "Como transformar biodiversidade em aplicação": "Cómo transformar biodiversidad en aplicación",
    "Um caminho orientado por ciência, dados e visão de mercado.": "Un camino orientado por ciencia, datos y visión de mercado.",
    "Ver todas as publicações →": "Ver todas las publicaciones →",
    "CORPO TÉCNICO": "EQUIPO CIENTÍFICO",
    "Liderança científica para soluções com bioativos naturais": "Liderazgo científico para soluciones con bioactivos naturales",
    "Parceiras estratégicas para empresas, laboratórios e instituições que buscam rigor técnico, evidências e inovação aplicada.": "Socias estratégicas para empresas, laboratorios e instituciones que buscan rigor técnico, evidencia e innovación aplicada.",
    "Pesquisa biomédica, P&DI e qualidade científica.": "Investigación biomédica, I+D+i y calidad científica.",
    "Liderança científica e empreendedora com atuação em pesquisa, desenvolvimento e estruturação de soluções com bioativos naturais.": "Liderazgo científico y emprendedor en investigación, desarrollo y estructuración de soluciones con bioactivos naturales.",
    "Fitoquímica, produtos naturais e ciência botânica aplicada.": "Fitoquímica, productos naturales y ciencia botánica aplicada.",
    "Pesquisadora com ampla experiência em produtos naturais, fitoquímica aplicada e desenvolvimento científico.": "Investigadora con amplia experiencia en productos naturales, fitoquímica aplicada y desarrollo científico.",
    "Ver LinkedIn →": "Ver LinkedIn →",
    "CONEXÕES OFICIAIS": "CONEXIONES OFICIALES",
    "Canais institucionais": "Canales institucionales",
    "Conecte-se com a PHYTOCHEM™ por nossos canais oficiais.": "Conéctese con PHYTOCHEM™ a través de nuestros canales oficiales.",
    "LinkedIn Corporativo": "LinkedIn Corporativo",
    "Instagram Oficial": "Instagram Oficial",
    "E-mail Comercial": "Correo comercial",
    "RECONHECIMENTOS E VINCULAÇÕES INSTITUCIONAIS": "RECONOCIMIENTOS Y VINCULACIONES INSTITUCIONALES",
    "Ciência conectada a um ecossistema de inovação.": "Ciencia conectada a un ecosistema de innovación.",
    "A PHYTOCHEM™ integra a rede de empresas-filhas da Unicamp, fortalecendo sua conexão com pesquisa, empreendedorismo científico e inovação aplicada.": "PHYTOCHEM™ integra la red de empresas-hijas de Unicamp, fortaleciendo su conexión con investigación, emprendimiento científico e innovación aplicada.",
    "// CONEXÃO CIENTÍFICA B2B": "// CONEXIÓN CIENTÍFICA B2B",
    "Vamos transformar biodiversidade em soluções com evidência científica?": "¿Transformamos la biodiversidad en soluciones con evidencia científica?",
    "Converse com a PHYTOCHEM™ para estruturar, validar ou desenvolver soluções com bioativos naturais, rastreabilidade técnica e visão de mercado.": "Hable con PHYTOCHEM™ para estructurar, validar o desarrollar soluciones con bioactivos naturales, trazabilidad técnica y visión de mercado.",
    "Falar com a Phytochem": "Hablar con Phytochem",
    "Conhecer soluções": "Conocer soluciones",
    "Navegação": "Navegación",
    "Conexões Oficiais": "Conexiones Oficiales",
    "P&DI em Ciência Botânica Aplicada.": "I+D+i en Ciencia Botánica Aplicada.",
    "Bioativos naturais com evidência científica.": "Bioactivos naturales con evidencia científica.",
    "Ciência · Rastreabilidade · Evidência": "Ciencia · Trazabilidad · Evidencia",
    "AGENDA B2B": "AGENDA B2B",
    "Agende uma conversa científica": "Agende una conversación científica",
    "Escolha uma data e um horário. Ao continuar, o Google Calendar abrirá o convite com a equipe comercial da PHYTOCHEM™.": "Elija una fecha y hora. Al continuar, Google Calendar abrirá una invitación con el equipo comercial de PHYTOCHEM™.",
    "Data": "Fecha",
    "Horário": "Hora",
    "Duração": "Duración",
    "Assunto": "Asunto",
    "45 minutos": "45 minutos",
    "60 minutos": "60 minutos",
    "Continuar no Google Calendar": "Continuar en Google Calendar",
    "O convite será preparado com comercial@phytochem.com.br como participante.": "La invitación se preparará con comercial@phytochem.com.br como participante.",
    "Fechar agenda": "Cerrar agenda",
    "Ex.: Projeto com bioativos naturais": "Ej.: Proyecto con bioactivos naturales",
    "PHYTOCHEM™ | P&DI em Ciência Botânica Aplicada e Bioativos Naturais": "PHYTOCHEM™ | P&DI em Ciência Botânica Aplicada e Bioativos Naturais",
    "P&DI": "P&DI",
    "Insights": "Insights",
    "PT": "PT",
    "EN": "EN",
    "ES": "ES",
    "PHYTOCHEM™": "PHYTOCHEM™",
    "•": "•",
    "B2B CAPABILITIES": "B2B CAPABILITIES",
    "01": "01",
    "02": "02",
    "03": "03",
    "04": "04",
    "05": "05",
    "06": "06",
    "01 / DESCOBRIR": "01 / DESCOBRIR",
    "02 / DECODIFICAR": "02 / DECODIFICAR",
    "03 / ISOLAR": "03 / ISOLAR",
    "04 / VALIDAR": "04 / VALIDAR",
    "07": "07",
    "08": "08",
    "09": "09",
    "⌁": "⌁",
    "◇": "◇",
    "⚗": "⚗",
    "≋": "≋",
    "◈": "◈",
    "◎": "◎",
    "⌬": "⌬",
    "✓": "✓",
    "Green Chemistry": "Green Chemistry",
    "P&DI · 8 MIN": "P&DI · 8 MIN",
    "CEO & FOUNDER": "CEO & FOUNDER",
    "Aline Borges Reche": "Aline Borges Reche",
    "CHIEF SCIENTIFIC OFFICER": "CHIEF SCIENTIFIC OFFICER",
    "Ilza Maria Oliveira Sousa": "Ilza Maria Oliveira Sousa",
    "in": "in",
    "linkedin.com/company/phytochemlab": "linkedin.com/company/phytochemlab",
    "@phytochem.lab": "@phytochem.lab",
    "@": "@",
    "comercial@phytochem.com.br": "comercial@phytochem.com.br",
    "×": "×",
    "© PHYTOCHEM™. Todos os direitos reservados.": "© PHYTOCHEM™. Todos os direitos reservados.",
    "PHYTOCHEM - início": "PHYTOCHEM - início",
    "PHYTOCHEM": "PHYTOCHEM",
    "Navegação principal": "Navegação principal",
    "Selecionar idioma": "Selecionar idioma",
    "Português": "Português",
    "English": "English",
    "Español": "Español",
    "Pipeline de inovação": "Pipeline de inovação",
    "Pipeline de isolamento de compostos bioativos": "Pipeline de isolamento de compostos bioativos",
    "Cadeia botânica responsável integrada a processos científicos sustentáveis": "Cadeia botânica responsável integrada a processos científicos sustentáveis",
    "Extrato botânico e fingerprint fitoquímico": "Extrato botânico e fingerprint fitoquímico",
    "Instrumentação analítica gerando evidências científicas": "Instrumentação analítica gerando evidências científicas",
    "Espécime botânico conectado à pesquisa aplicada": "Espécime botânico conectado à pesquisa aplicada",
    "Aline Borges Reche, CEO e fundadora da Phytochem": "Aline Borges Reche, CEO e fundadora da Phytochem",
    "Ilza Maria Oliveira Sousa, Chief Scientific Officer da Phytochem": "Ilza Maria Oliveira Sousa, Chief Scientific Officer da Phytochem",
    "Selo oficial Empresa-Filha da Unicamp": "Selo oficial Empresa-Filha da Unicamp"
  }
};
