// Conteudo editavel em portugues. Altere somente os valores apos os dois-pontos.
window.PHYTOCHEM_CONTENT = window.PHYTOCHEM_CONTENT || {};
window.PHYTOCHEM_CONTENT.pt = {
  "meta": {
    "lang": "pt-BR",
    "title": "PHYTOCHEM™ | P&DI em Ciência Botânica Aplicada e Bioativos Naturais",
    "description": "A PHYTOCHEM™ transforma biodiversidade em soluções aplicadas com evidências científicas, desenvolvendo projetos com bioativos naturais, fitoquímica, isolamento, rastreabilidade e aplicações industriais."
  },
  "links": {
    "siteUrl": "https://joelalbertofernandes.github.io/Phytochem/",
    "linkedinCompany": "https://www.linkedin.com/company/phytochemlab/",
    "instagram": "https://www.instagram.com/phytochem.lab/",
    "alineLinkedIn": "https://www.linkedin.com/in/alineborgesreche/",
    "ilzaLinkedIn": "https://www.linkedin.com/in/ilza-maria-oliveira-sousa-48b1352b9/",
    "commercialEmail": "comercial@phytochem.com.br",
    "linkedinCompanyLabel": "linkedin.com/company/phytochemlab",
    "instagramLabel": "@phytochem.lab"
  },
  "scheduler": {
    "defaultSubject": "Conversa científica B2B com a PHYTOCHEM",
    "details": "Conversa sobre P&DI em Ciência Botânica Aplicada e soluções com bioativos naturais."
  },
  "texts": {
    "Ir para o conteúdo": "Ir para o conteúdo",
    "Início": "Início",
    "Sobre": "Sobre",
    "Soluções": "Soluções",
    "Sustentabilidade": "Sustentabilidade",
    "Corpo técnico": "Corpo técnico",
    "Contato": "Contato",
    "Agendar conversa": "Agendar conversa",
    "Abrir menu": "Abrir menu",
    "Fechar menu": "Fechar menu",
    "// CIÊNCIA BOTÂNICA APLICADA": "// CIÊNCIA BOTÂNICA APLICADA",
    "Bioativos naturais com": "Bioativos naturais com",
    "evidência científica.": "evidência científica.",
    "Transformamos biodiversidade em soluções aplicadas com evidências científicas.": "Transformamos biodiversidade em soluções aplicadas com evidências científicas.",
    "Conectamos biodiversidade, fitoquímica e tecnologia analítica ao desenvolvimento de soluções com bioativos naturais, rastreabilidade, isolamento e validação técnico-científica.": "Conectamos biodiversidade, fitoquímica e tecnologia analítica ao desenvolvimento de soluções com bioativos naturais, rastreabilidade, isolamento e validação técnico-científica.",
    "Conheça nossas soluções": "Conheça nossas soluções",
    "Pesquisa": "Pesquisa",
    "Fitoquímica": "Fitoquímica",
    "Isolamento": "Isolamento",
    "Evidências": "Evidências",
    "Aplicações industriais": "Aplicações industriais",
    "Descobrir": "Descobrir",
    "// CONCEITO CENTRAL": "// CONCEITO CENTRAL",
    "A natureza sempre teve respostas.": "A natureza sempre teve respostas.",
    "A ciência agora permite decodificá-las.": "A ciência agora permite decodificá-las.",
    "A Phytochem une P&DI, fitoquímica aplicada e tecnologia analítica para transformar biodiversidade em soluções com bioativos naturais, evidências técnicas, rastreabilidade e aplicações industriais.": "A Phytochem une P&DI, fitoquímica aplicada e tecnologia analítica para transformar biodiversidade em soluções com bioativos naturais, evidências técnicas, rastreabilidade e aplicações industriais.",
    "Mais do que um laboratório, atuamos como uma plataforma científica para o desenvolvimento de soluções naturais com precisão, método, evidências e visão de mercado.": "Mais do que um laboratório, atuamos como uma plataforma científica para o desenvolvimento de soluções naturais com precisão, método, evidências e visão de mercado.",
    "Soluções científicas para bioativos naturais": "Soluções científicas para bioativos naturais",
    "Da análise ao desenvolvimento: suporte técnico para empresas que desejam criar, validar, padronizar e escalar soluções com bioativos naturais.": "Da análise ao desenvolvimento: suporte técnico para empresas que desejam criar, validar, padronizar e escalar soluções com bioativos naturais.",
    "Análise fitoquímica": "Análise fitoquímica",
    "Identificação, caracterização e avaliação de compostos presentes em matrizes naturais.": "Identificação, caracterização e avaliação de compostos presentes em matrizes naturais.",
    "Fitoquímica aplicada →": "Fitoquímica aplicada →",
    "Mapeamos e caracterizamos o perfil químico de insumos e matrizes naturais, apoiando decisões técnicas e geração de evidências.": "Mapeamos e caracterizamos o perfil químico de insumos e matrizes naturais, apoiando decisões técnicas e geração de evidências.",
    "Saiba mais →": "Saiba mais →",
    "Desenvolvimento de produtos com bioativos": "Desenvolvimento de produtos com bioativos",
    "Soluções para aplicações cosméticas, farmacêuticas e industriais.": "Soluções para aplicações cosméticas, farmacêuticas e industriais.",
    "Inovação e P&DI →": "Inovação e P&DI →",
    "Desenvolvimento com bioativos": "Desenvolvimento com bioativos",
    "Conectamos seleção de insumos, evidências, padronização, viabilidade técnica e direcionamento de aplicação.": "Conectamos seleção de insumos, evidências, padronização, viabilidade técnica e direcionamento de aplicação.",
    "Padronização de extratos": "Padronização de extratos",
    "Parâmetros técnicos, fingerprints, especificações e controle de qualidade.": "Parâmetros técnicos, fingerprints, especificações e controle de qualidade.",
    "Garantia técnica →": "Garantia técnica →",
    "Estruturamos processos para assegurar consistência, repetibilidade analítica, rastreabilidade e desempenho industrial.": "Estruturamos processos para assegurar consistência, repetibilidade analítica, rastreabilidade e desempenho industrial.",
    "Química analítica e evidências": "Química analítica e evidências",
    "Métodos analíticos voltados ao controle, validação e geração de evidências.": "Métodos analíticos voltados ao controle, validação e geração de evidências.",
    "Evidências científicas →": "Evidências científicas →",
    "Química analítica": "Química analítica",
    "Aplicamos química analítica para apoiar controle, validação, estudos comparativos e geração de evidências técnicas.": "Aplicamos química analítica para apoiar controle, validação, estudos comparativos e geração de evidências técnicas.",
    "Pesquisa aplicada e desenvolvimento": "Pesquisa aplicada e desenvolvimento",
    "Suporte científico para projetos orientados à inovação e aplicações.": "Suporte científico para projetos orientados à inovação e aplicações.",
    "Pesquisa aplicada →": "Pesquisa aplicada →",
    "Pesquisa aplicada": "Pesquisa aplicada",
    "Transformamos biodiversidade em soluções com valor técnico e potencial de mercado por meio de ciência aplicada.": "Transformamos biodiversidade em soluções com valor técnico e potencial de mercado por meio de ciência aplicada.",
    "Consultoria científica B2B": "Consultoria científica B2B",
    "Orientação estratégica para desenvolver, validar e posicionar soluções.": "Orientação estratégica para desenvolver, validar e posicionar soluções.",
    "Estratégia científica →": "Estratégia científica →",
    "Estruturamos caminhos de desenvolvimento, priorização de estudos, aplicações e diferenciação científica.": "Estruturamos caminhos de desenvolvimento, priorização de estudos, aplicações e diferenciação científica.",
    "PRODUÇÃO DE CONHECIMENTO": "PRODUÇÃO DE CONHECIMENTO",
    "P&DI em Ciência Botânica Aplicada": "P&DI em Ciência Botânica Aplicada",
    "Integramos ciência, dados, biodiversidade e tecnologia para acelerar o desenvolvimento de soluções com bioativos naturais.": "Integramos ciência, dados, biodiversidade e tecnologia para acelerar o desenvolvimento de soluções com bioativos naturais.",
    "Leitura científica da biodiversidade": "Leitura científica da biodiversidade",
    "Análise técnica para identificar oportunidades estruturadas em bioativos naturais e aplicações de alto valor.": "Análise técnica para identificar oportunidades estruturadas em bioativos naturais e aplicações de alto valor.",
    "P&D orientado por dados": "P&D orientado por dados",
    "Pesquisa analítica guiada por dados, evidências e caracterização molecular.": "Pesquisa analítica guiada por dados, evidências e caracterização molecular.",
    "Extração e isolamento de precisão": "Extração e isolamento de precisão",
    "Frações direcionadas com foco em rendimento, estabilidade fitoquímica e aplicação.": "Frações direcionadas com foco em rendimento, estabilidade fitoquímica e aplicação.",
    "Validação técnico-científica": "Validação técnico-científica",
    "Evidências consistentes para transformar descobertas naturais em soluções aplicáveis.": "Evidências consistentes para transformar descobertas naturais em soluções aplicáveis.",
    "ROADMAP CIENTÍFICO": "ROADMAP CIENTÍFICO",
    "Pipeline Phytochem de Inovação Aplicada": "Pipeline Phytochem de Inovação Aplicada",
    "Da biodiversidade às aplicações com bioativos naturais, por meio de evidências, isolamento, validação e direcionamento técnico.": "Da biodiversidade às aplicações com bioativos naturais, por meio de evidências, isolamento, validação e direcionamento técnico.",
    "Descoberta": "Descoberta",
    "Caracterização": "Caracterização",
    "Validação": "Validação",
    "Aplicação": "Aplicação",
    "Escala": "Escala",
    "Biodiversidade": "Biodiversidade",
    "Seleção botânica": "Seleção botânica",
    "Extração": "Extração",
    "Transferência": "Transferência",
    "PIPELINE EXCLUSIVA": "PIPELINE EXCLUSIVA",
    "Isolamento de Compostos Bioativos": "Isolamento de Compostos Bioativos",
    "Uma jornada científica independente, orientada à obtenção, purificação e validação de compostos naturais com precisão analítica.": "Uma jornada científica independente, orientada à obtenção, purificação e validação de compostos naturais com precisão analítica.",
    "Coleta Botânica": "Coleta Botânica",
    "Origem responsável e seleção criteriosa.": "Origem responsável e seleção criteriosa.",
    "Preparação da Matéria-Prima": "Preparação da Matéria-Prima",
    "Tratamento técnico para preservar o potencial químico.": "Tratamento técnico para preservar o potencial químico.",
    "Processos dirigidos por rendimento e seletividade.": "Processos dirigidos por rendimento e seletividade.",
    "Fracionamento": "Fracionamento",
    "Separação orientada pelo perfil fitoquímico.": "Separação orientada pelo perfil fitoquímico.",
    "Purificação": "Purificação",
    "Refinamento progressivo de frações de interesse.": "Refinamento progressivo de frações de interesse.",
    "Obtenção de compostos com identidade definida.": "Obtenção de compostos com identidade definida.",
    "Caracterização Analítica": "Caracterização Analítica",
    "Elucidação e confirmação técnico-analítica.": "Elucidação e confirmação técnico-analítica.",
    "Validação Científica": "Validação Científica",
    "Evidências consistentes para aplicações futuras.": "Evidências consistentes para aplicações futuras.",
    "Projeto P&DI 01": "Projeto P&DI 01",
    "Isolamento e caracterização de frações bioativas": "Isolamento e caracterização de frações bioativas",
    "Produto / aplicação": "Produto / aplicação",
    "Transferência B2B": "Transferência B2B",
    "◈ Propriedade intelectual": "◈ Propriedade intelectual",
    "⌁ Codesenvolvimento": "⌁ Codesenvolvimento",
    "▤ Evidências técnico-científicas": "▤ Evidências técnico-científicas",
    "⚗ Aplicação industrial": "⚗ Aplicação industrial",
    "⚙ Transferência tecnológica": "⚙ Transferência tecnológica",
    "MERCADOS-CHAVE": "MERCADOS-CHAVE",
    "Onde os bioativos naturais geram valor": "Onde os bioativos naturais geram valor",
    "Soluções rastreáveis e suporte técnico-científico para mercados de alta exigência.": "Soluções rastreáveis e suporte técnico-científico para mercados de alta exigência.",
    "Cosméticos e dermocosméticos": "Cosméticos e dermocosméticos",
    "Suplementos e alimentos funcionais": "Suplementos e alimentos funcionais",
    "Farmacêutico e saúde": "Farmacêutico e saúde",
    "Ingredientes naturais e funcionais": "Ingredientes naturais e funcionais",
    "Indústria de ingredientes": "Indústria de ingredientes",
    "Pesquisa acadêmica e aplicada": "Pesquisa acadêmica e aplicada",
    "Bioativos naturais e suporte técnico para formulações premium.": "Bioativos naturais e suporte técnico para formulações premium.",
    "Compostos naturais, padronização e suporte ao desenvolvimento.": "Compostos naturais, padronização e suporte ao desenvolvimento.",
    "Pesquisa, isolamento, validação e documentação de alto rigor.": "Pesquisa, isolamento, validação e documentação de alto rigor.",
    "Diferenciação científica para produtos de valor agregado.": "Diferenciação científica para produtos de valor agregado.",
    "Ingredientes naturais rastreáveis, consistentes e diferenciados.": "Ingredientes naturais rastreáveis, consistentes e diferenciados.",
    "Apoio a universidades, startups e projetos colaborativos.": "Apoio a universidades, startups e projetos colaborativos.",
    "// METODOLOGIA SUSTENTÁVEL": "// METODOLOGIA SUSTENTÁVEL",
    "Ciência natural com responsabilidade": "Ciência natural com responsabilidade",
    "Sustentabilidade como método: origem responsável, rastreabilidade, eficiência, valorização da biodiversidade e menor impacto ambiental.": "Sustentabilidade como método: origem responsável, rastreabilidade, eficiência, valorização da biodiversidade e menor impacto ambiental.",
    "Biodiversidade brasileira": "Biodiversidade brasileira",
    "Cadeias locais": "Cadeias locais",
    "Saberes tradicionais": "Saberes tradicionais",
    "Rastreabilidade": "Rastreabilidade",
    "Valorização de resíduos": "Valorização de resíduos",
    "Valorização científica, legal e sustentável dos recursos naturais.": "Valorização científica, legal e sustentável dos recursos naturais.",
    "Integração responsável com territórios produtivos e parceiros.": "Integração responsável com territórios produtivos e parceiros.",
    "Abordagem ética, respeito cultural e observância legal.": "Abordagem ética, respeito cultural e observância legal.",
    "Eficiência, redução de resíduos e racionalidade técnica.": "Eficiência, redução de resíduos e racionalidade técnica.",
    "Controle documental desde a origem até a aplicação.": "Controle documental desde a origem até a aplicação.",
    "Upcycling de coprodutos em novas oportunidades de aplicação.": "Upcycling de coprodutos em novas oportunidades de aplicação.",
    "HUB EDITORIAL": "HUB EDITORIAL",
    "Insights Científicos": "Insights Científicos",
    "Conhecimento e evidências para empresas e parceiros que priorizam inovação botânica aplicada.": "Conhecimento e evidências para empresas e parceiros que priorizam inovação botânica aplicada.",
    "FITOQUÍMICA APLICADA · 6 MIN": "FITOQUÍMICA APLICADA · 6 MIN",
    "EVIDÊNCIAS · 5 MIN": "EVIDÊNCIAS · 5 MIN",
    "Da matriz natural ao fingerprint: por que padronizar?": "Da matriz natural ao fingerprint: por que padronizar?",
    "Consistência analítica como base para inovação com bioativos.": "Consistência analítica como base para inovação com bioativos.",
    "Evidências técnicas que fortalecem decisões B2B": "Evidências técnicas que fortalecem decisões B2B",
    "O papel da química analítica na confiança e diferenciação.": "O papel da química analítica na confiança e diferenciação.",
    "Como transformar biodiversidade em aplicação": "Como transformar biodiversidade em aplicação",
    "Um caminho orientado por ciência, dados e visão de mercado.": "Um caminho orientado por ciência, dados e visão de mercado.",
    "Ver todas as publicações →": "Ver todas as publicações →",
    "CORPO TÉCNICO": "CORPO TÉCNICO",
    "Liderança científica para soluções com bioativos naturais": "Liderança científica para soluções com bioativos naturais",
    "Parceiras estratégicas para empresas, laboratórios e instituições que buscam rigor técnico, evidências e inovação aplicada.": "Parceiras estratégicas para empresas, laboratórios e instituições que buscam rigor técnico, evidências e inovação aplicada.",
    "Pesquisa biomédica, P&DI e qualidade científica.": "Pesquisa biomédica, P&DI e qualidade científica.",
    "Liderança científica e empreendedora com atuação em pesquisa, desenvolvimento e estruturação de soluções com bioativos naturais.": "Liderança científica e empreendedora com atuação em pesquisa, desenvolvimento e estruturação de soluções com bioativos naturais.",
    "Fitoquímica, produtos naturais e ciência botânica aplicada.": "Fitoquímica, produtos naturais e ciência botânica aplicada.",
    "Pesquisadora com ampla experiência em produtos naturais, fitoquímica aplicada e desenvolvimento científico.": "Pesquisadora com ampla experiência em produtos naturais, fitoquímica aplicada e desenvolvimento científico.",
    "Ver LinkedIn →": "Ver LinkedIn →",
    "CONEXÕES OFICIAIS": "CONEXÕES OFICIAIS",
    "Canais institucionais": "Canais institucionais",
    "Conecte-se com a PHYTOCHEM™ por nossos canais oficiais.": "Conecte-se com a PHYTOCHEM™ por nossos canais oficiais.",
    "LinkedIn Corporativo": "LinkedIn Corporativo",
    "Instagram Oficial": "Instagram Oficial",
    "E-mail Comercial": "E-mail Comercial",
    "RECONHECIMENTOS E VINCULAÇÕES INSTITUCIONAIS": "RECONHECIMENTOS E VINCULAÇÕES INSTITUCIONAIS",
    "Ciência conectada a um ecossistema de inovação.": "Ciência conectada a um ecossistema de inovação.",
    "A PHYTOCHEM™ integra a rede de empresas-filhas da Unicamp, fortalecendo sua conexão com pesquisa, empreendedorismo científico e inovação aplicada.": "A PHYTOCHEM™ integra a rede de empresas-filhas da Unicamp, fortalecendo sua conexão com pesquisa, empreendedorismo científico e inovação aplicada.",
    "// CONEXÃO CIENTÍFICA B2B": "// CONEXÃO CIENTÍFICA B2B",
    "Vamos transformar biodiversidade em soluções com evidência científica?": "Vamos transformar biodiversidade em soluções com evidência científica?",
    "Converse com a PHYTOCHEM™ para estruturar, validar ou desenvolver soluções com bioativos naturais, rastreabilidade técnica e visão de mercado.": "Converse com a PHYTOCHEM™ para estruturar, validar ou desenvolver soluções com bioativos naturais, rastreabilidade técnica e visão de mercado.",
    "Falar com a Phytochem": "Falar com a Phytochem",
    "Conhecer soluções": "Conhecer soluções",
    "Navegação": "Navegação",
    "Conexões Oficiais": "Conexões Oficiais",
    "P&DI em Ciência Botânica Aplicada.": "P&DI em Ciência Botânica Aplicada.",
    "Bioativos naturais com evidência científica.": "Bioativos naturais com evidência científica.",
    "Ciência · Rastreabilidade · Evidência": "Ciência · Rastreabilidade · Evidência",
    "AGENDA B2B": "AGENDA B2B",
    "Agende uma conversa científica": "Agende uma conversa científica",
    "Escolha uma data e um horário. Ao continuar, o Google Calendar abrirá o convite com a equipe comercial da PHYTOCHEM™.": "Escolha uma data e um horário. Ao continuar, o Google Calendar abrirá o convite com a equipe comercial da PHYTOCHEM™.",
    "Data": "Data",
    "Horário": "Horário",
    "Duração": "Duração",
    "Assunto": "Assunto",
    "45 minutos": "45 minutos",
    "60 minutos": "60 minutos",
    "Continuar no Google Calendar": "Continuar no Google Calendar",
    "O convite será preparado com comercial@phytochem.com.br como participante.": "O convite será preparado com comercial@phytochem.com.br como participante.",
    "Fechar agenda": "Fechar agenda",
    "Ex.: Projeto com bioativos naturais": "Ex.: Projeto com bioativos naturais",
    "PHYTOCHEM™ | P&DI em Ciência Botânica Aplicada e Bioativos Naturais": "PHYTOCHEM™ | P&DI em Ciência Botânica Aplicada e Bioativos Naturais",
    "P&DI": "P&DI",
    "Insights": "Insights",
    "PT": "PT",
    "EN": "EN",
    "ES": "ES",
    "PHYTOCHEM™": "PHYTOCHEM™",
    "•": "•",
    "B2B CAPABILITIES": "B2B CAPABILITIES",
    "01": "01",
    "02": "02",
    "03": "03",
    "04": "04",
    "05": "05",
    "06": "06",
    "01 / DESCOBRIR": "01 / DESCOBRIR",
    "02 / DECODIFICAR": "02 / DECODIFICAR",
    "03 / ISOLAR": "03 / ISOLAR",
    "04 / VALIDAR": "04 / VALIDAR",
    "07": "07",
    "08": "08",
    "09": "09",
    "⌁": "⌁",
    "◇": "◇",
    "⚗": "⚗",
    "≋": "≋",
    "◈": "◈",
    "◎": "◎",
    "⌬": "⌬",
    "✓": "✓",
    "Green Chemistry": "Green Chemistry",
    "P&DI · 8 MIN": "P&DI · 8 MIN",
    "CEO & FOUNDER": "CEO & FOUNDER",
    "Aline Borges Reche": "Aline Borges Reche",
    "CHIEF SCIENTIFIC OFFICER": "CHIEF SCIENTIFIC OFFICER",
    "Ilza Maria Oliveira Sousa": "Ilza Maria Oliveira Sousa",
    "in": "in",
    "linkedin.com/company/phytochemlab": "linkedin.com/company/phytochemlab",
    "@phytochem.lab": "@phytochem.lab",
    "@": "@",
    "comercial@phytochem.com.br": "comercial@phytochem.com.br",
    "×": "×",
    "© PHYTOCHEM™. Todos os direitos reservados.": "© PHYTOCHEM™. Todos os direitos reservados.",
    "PHYTOCHEM - início": "PHYTOCHEM - início",
    "PHYTOCHEM": "PHYTOCHEM",
    "Navegação principal": "Navegação principal",
    "Selecionar idioma": "Selecionar idioma",
    "Português": "Português",
    "English": "English",
    "Español": "Español",
    "Pipeline de inovação": "Pipeline de inovação",
    "Pipeline de isolamento de compostos bioativos": "Pipeline de isolamento de compostos bioativos",
    "Cadeia botânica responsável integrada a processos científicos sustentáveis": "Cadeia botânica responsável integrada a processos científicos sustentáveis",
    "Extrato botânico e fingerprint fitoquímico": "Extrato botânico e fingerprint fitoquímico",
    "Instrumentação analítica gerando evidências científicas": "Instrumentação analítica gerando evidências científicas",
    "Espécime botânico conectado à pesquisa aplicada": "Espécime botânico conectado à pesquisa aplicada",
    "Aline Borges Reche, CEO e fundadora da Phytochem": "Aline Borges Reche, CEO e fundadora da Phytochem",
    "Ilza Maria Oliveira Sousa, Chief Scientific Officer da Phytochem": "Ilza Maria Oliveira Sousa, Chief Scientific Officer da Phytochem",
    "Selo oficial Empresa-Filha da Unicamp": "Selo oficial Empresa-Filha da Unicamp"
  }
};
